### ISSUE TITLE
Need your help about Focs model train

### ISSUE THREAD

**Issue by bovane** [delmalih/mias-mammography-obj-detection#4]
@delmalih 
I'm training the focs model with google colab ,but it can't work when I follow the instructions.
Colab configuration are as follows:
torch.version.cuda-----
Cuda compilation tools, release 10.1, V10.1.243
print(torch.__version__) -----
1.4.0
print(torch.cuda.is_available())
print(torch.backends.cudnn.enabled)--------
True
True

the details for error---------------
Traceback (most recent call last):
  File "train.py", line 180, in <module>
    main()
  File "train.py", line 173, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "train.py", line 79, in train
    arguments
  File "/content/drive/Shared drives/BoVane/dependency/FCOS/fcos_core/engine/trainer.py", line 69, in do_train
    loss_dict = model(images, targets)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/drive/Shared drives/BoVane/dependency/FCOS/fcos_core/modeling/detector/generalized_rcnn.py", line 50, in forward
    proposals, proposal_losses = self.rpn(images, features, targets)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/drive/Shared drives/BoVane/dependency/FCOS/fcos_core/modeling/rpn/fcos/fcos.py", line 159, in forward
    centerness, targets
  File "/content/drive/Shared drives/BoVane/dependency/FCOS/fcos_core/modeling/rpn/fcos/fcos.py", line 169, in _forward_train
    locations, box_cls, box_regression, centerness, targets
  File "/content/drive/Shared drives/BoVane/dependency/FCOS/fcos_core/modeling/rpn/fcos/loss.py", line 257, in __call__
    labels_flatten.int()
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/drive/Shared drives/BoVane/dependency/FCOS/fcos_core/layers/sigmoid_focal_loss.py", line 68, in forward
    loss = loss_func(logits, targets, self.gamma, self.alpha)
  File "/content/drive/Shared drives/BoVane/dependency/FCOS/fcos_core/layers/sigmoid_focal_loss.py", line 19, in forward
    logits, targets, num_classes, gamma, alpha
RuntimeError: Not compiled with GPU support (SigmoidFocalLoss_forward at fcos_core/csrc/SigmoidFocalLoss.h:20)

Please help me !!! Thank you 🙏 😊

**Comment by delmalih** [comment]
For the FCOS obj. detector training, I'd recommend you to use the official [repo](https://github.com/tianzhi0549/FCOS)

**Comment by bovane** [comment]
Thank you David，I have send a email to you，could you reply me ? please ! @delmalih

**Comment by bovane** [comment]
<img width="581" alt="截屏2020-04-22 下午7 56 15" src="https://user-images.githubusercontent.com/40169572/79978951-56f3b700-84d3-11ea-99d6-aa484f15866d.png">
How can I get such output ？！！

**Comment by bovane** [comment]
@delmalih 
I am so sorry for my interruption，Please forgive me for interrupting.
I have trained the faster-rcnn,fcos,and retinanet,but I can't get the output as your picture,please help me! I have sent the email to you,I introduced more information in the email,could you reply me? I need whole codes and documents about this project.I promise I will only use it for personal learning ！If you can help me, I will pray for you all day long！Thank you ! 🙏 😊 ☺️ David
